server:
  port: 8686
  servlet:
    context-path: /notification-api/v1.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  hibernate:
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: payment-group,order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.common.serializer.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.rentme.app.event.OrderConfirmation,paymentConfirmation:com.rentme.app.event.PaymentConfirmation

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
