server:
  port: 8787
  servlet:
    context-path: /order-api/v1.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  hibernate:
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

application:
  config:
    authorization-url: http://localhost:authorization-service/auth-api/v1.0.0
    product-url: http://localhost:product-service/product-api/v1.0.0
    payment-url: http://localhost:payment-service/payment-api/v1.0.0