spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: cart-service

application:
  config:
    product-url: http://localhost:9090/product-api/v1.0.0
    authorization-url: http://localhost:8080